"""empty message

Revision ID: a73158cc4a95
Revises: None
Create Date: 2021-11-03 23:19:37.450547

"""

# revision identifiers, used by Alembic.
revision = 'a73158cc4a95'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=8), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('modificado_em', sa.DateTime(), nullable=True),
    sa.Column('valor1', sa.Float(), nullable=False),
    sa.Column('valor2', sa.Float(), nullable=True),
    sa.Column('operacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operacao'], ['operacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equacoes')
    op.drop_table('operacoes')
    # ### end Alembic commands ###
