"""empty message

Revision ID: a9fcb9872d10
Revises: None
Create Date: 2021-11-08 20:57:21.383852

"""

# revision identifiers, used by Alembic.
revision = 'a9fcb9872d10'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=8), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mudancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('modificado_em', sa.DateTime(), nullable=True),
    sa.Column('cotg', sa.String(length=64), nullable=True),
    sa.Column('valor1', sa.Float(), nullable=False),
    sa.Column('valor2', sa.Float(), nullable=True),
    sa.Column('resposta', sa.String(length=64), nullable=True),
    sa.Column('equacao', sa.Integer(), nullable=True),
    sa.Column('operacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equacao'], ['equacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operacao'], ['operacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mudancas')
    op.drop_table('operacoes')
    op.drop_table('equacoes')
    # ### end Alembic commands ###
